description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: sh
    - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
      with:
        cache: 'yarn'
        node-version-file: '.node-version'
    - run: yarn install --immutable --mode=skip-build
      shell: sh
