description: Provides Common Setup for Workflows Dependent on NodeJS
name: setup-node

runs:
  using: composite
  steps:
    - run: corepack enable
      shell: sh
    - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        cache: 'yarn'
        node-version-file: '.node-version'
    - run: yarn install --immutable --mode=skip-build
      shell: sh
